---
title: "Kitty Act V1 Analysis"
author: "Martin Zettersten"
date: "2024-04-24"
output:
  pdf_document: default
  html_document: default
---
  
```{r setup, warning=FALSE, message=F}
library(here)
library(tidyverse)
library(ggplot2)
library(viridisLite)
library(lme4)
library(ggstance)
library(cowplot)
library(AICcmodavg)
library(RColorBrewer)
library(jsonlite)
library(tidyjson)
library(rlang)
library(car)
library(nnet)
library(mlogit)
library(lmerTest)
library(assertthat)
source("helper.R")

data_path <- here("processed_data", "kitty-act-v1-alldata.csv")
sampling_data_path <- here("processed_data", "kitty-act-v1-processed_data_sampling.csv")
test_data_path <- here("processed_data", "kitty-act-v1-processed_data.csv")
test_data_long_path <- here("processed_data", "kitty-act-v1-processed_data_long.csv")
write_path <- here("processed_data")
figure_path <- here("figures")
```

# Data Processing

## Read in data

```{r, warning=FALSE, message=F}
d <- read_csv(data_path)
sampling_data <- read_csv(sampling_data_path)
test_array_clean <- read_csv(test_data_path)
test_array_options_clean <- read_csv(test_data_long_path)
```

## run a couple of tests on the data

```{r}
#check that we have all of the participants we expect
assert_that(length(unique(sampling_data$subject_id))==length(unique(test_array_clean$subject_id)))
assert_that(length(unique(sampling_data$subject_id))==83)
```


## Summarize Test Data

```{r}
## shorter test representation
subj_test_accuracy <- test_array_clean %>%
  group_by(participant,number_training_images,round,trial_counter,trial_type,current_category_training_level,current_category_label_level,current_category_kind,final_choice_array,total_number_correct_options) %>%
  summarize(
    total_choices = n(),
    ground_truth_correct_choices = sum(test_choice_type_label_consistent),
    ground_truth_incorrect_choices = sum(test_choice_type_label_consistent==0),
    training_consistent_choices = sum(test_choice_type_training_consistent),
    training_inconsistent_choices = sum(test_choice_type_training_consistent==0),
    training_category_match_subordinate_choices = sum(test_choice_match_category==1 & test_choice_type == "subordinate"),
    training_category_match_basic_choices = sum(test_choice_match_category==1 & test_choice_type == "basic"),
    training_category_match_superordinate_choices = sum(test_choice_match_category==1 & test_choice_type == "superordinate"),
    training_category_match_subordinate_percent = training_category_match_subordinate_choices,
    training_category_match_basic_percent = training_category_match_basic_choices,
    training_category_match_superordinate_percent = training_category_match_superordinate_choices/2
  )

subj_test_accuracy_long <- subj_test_accuracy %>%
  select(participant,number_training_images,round,trial_counter,trial_type,current_category_training_level,current_category_label_level,current_category_kind,final_choice_array,total_number_correct_options,training_category_match_subordinate_percent,training_category_match_basic_percent,training_category_match_superordinate_percent) %>%
  group_by(participant,number_training_images,round,trial_counter,trial_type,current_category_training_level,current_category_label_level,current_category_kind,final_choice_array,total_number_correct_options) %>%
  pivot_longer(cols=training_category_match_subordinate_percent:training_category_match_superordinate_percent,names_to = "choice_type",values_to = "percent_chosen")

overall_accuracy_by_condition <- subj_test_accuracy_long %>%
  ungroup() %>%
  group_by(number_training_images,current_category_training_level,choice_type) %>%
  summarize(
    N=n(),
    average_percent=mean(percent_chosen)
  ) %>%
  mutate(
    choice_type = str_remove(choice_type,"training_category_match_"),
    choice_type = str_remove(choice_type,"_percent")
  )

overall_accuracy_by_condition_round <- subj_test_accuracy_long %>%
  ungroup() %>%
  group_by(round,number_training_images,current_category_training_level,choice_type) %>%
  summarize(
    N=n(),
    average_percent=mean(percent_chosen)
  ) %>%
  mutate(
    choice_type = str_remove(choice_type,"training_category_match_"),
    choice_type = str_remove(choice_type,"_percent")
  )

overall_accuracy_label_level_by_condition <- subj_test_accuracy_long %>%
  ungroup() %>%
  group_by(number_training_images,current_category_training_level,current_category_label_level,choice_type) %>%
  summarize(
    N=n(),
    average_percent=mean(percent_chosen)
  ) %>%
  mutate(
    choice_type = str_remove(choice_type,"training_category_match_"),
    choice_type = str_remove(choice_type,"_percent")
  )

overall_accuracy_label_level_by_condition_round <- subj_test_accuracy_long %>%
  ungroup() %>%
  group_by(round,number_training_images,current_category_training_level,current_category_label_level,choice_type) %>%
  summarize(
    N=n(),
    average_percent=mean(percent_chosen)
  ) %>%
  mutate(
    choice_type = str_remove(choice_type,"training_category_match_"),
    choice_type = str_remove(choice_type,"_percent")
  )


### longer test representation
subj_test_accuracy_all <- test_array_options_clean %>%
  group_by(participant,number_training_images,round,trial_counter,trial_type,current_category_training_level,current_category_label_level,current_category_kind,final_choice_array,total_number_correct_options_label,total_number_correct_options_training) %>%
  summarize(
    accuracy_training = mean(is_match_to_training, na.rm=TRUE),
    accuracy_label = mean(is_match_to_label,na.rm=TRUE),
    hit_rate_training = mean(hit_training,na.rm=TRUE),
    hit_rate_label = mean(hit_label,na.rm=TRUE),
    false_alarm_rate_training = mean(false_alarm_training,na.rm=TRUE),
    false_alarm_rate_label = mean(false_alarm_label,na.rm=TRUE)
  ) %>%
  mutate(
    hit_rate_training_adj= case_when(
      hit_rate_training==1 ~ 1 - 1/(2*total_number_correct_options_training),
      hit_rate_training==0 ~ 1/(2*total_number_correct_options_training),
      TRUE ~ hit_rate_training
    ),
    hit_rate_label_adj= case_when(
      hit_rate_label==1 ~ 1 - 1/(2*total_number_correct_options_label),
      hit_rate_label==0 ~ 1/(2*total_number_correct_options_label),
      TRUE ~ hit_rate_label
    ),
    false_alarm_rate_training_adj= case_when(
      false_alarm_rate_training==0 ~ 1/(2*total_number_correct_options_training),
      false_alarm_rate_training==1 ~ 1 - 1/(2*total_number_correct_options_training),
      TRUE ~ false_alarm_rate_training
    ),
    false_alarm_rate_label_adj= case_when(
      false_alarm_rate_label==0 ~ 1/(2*total_number_correct_options_label),
      false_alarm_rate_label==1 ~ 1 - 1/(2*total_number_correct_options_label),
      TRUE ~ false_alarm_rate_label
    )
  ) %>%
  mutate(
    dprime_training=qnorm(hit_rate_training_adj) - qnorm(false_alarm_rate_training_adj),
    dprime_label=qnorm(hit_rate_label_adj) - qnorm(false_alarm_rate_label_adj),
    c_training=-.5*(qnorm(hit_rate_training_adj) + qnorm(false_alarm_rate_training_adj)),
    c_label=-.5*(qnorm(hit_rate_label_adj) + qnorm(false_alarm_rate_label_adj)))

subj_test_accuracy_all <- subj_test_accuracy_all %>%
  left_join(sampling_data)

overall_accuracy_label_level_sampling_all <- subj_test_accuracy_all %>%
  ungroup() %>%
  group_by(sampling_choice_type,current_category_training_level,current_category_label_level) %>%
  summarize(
    N=n(),
    average_dprime_training=mean(dprime_training),
    average_dprime_label=mean(dprime_label)
  ) 
```

## Sampling

### Plot

```{r}
sampling_data$sampled_category_level_kind_info_ord <- factor(sampling_data$sampled_category_level_kind_info,
                                                             levels=c("sub","bas","sup","outside_category"),
                                                             labels=c("subordinate","basic","superordinate","outside category"))
sampling_data$current_category_training_level_ord <- factor(sampling_data$current_category_training_level,levels=c("narrow","intermediate","broad"))

ggplot(sampling_data,aes(current_category_training_level_ord,fill=sampled_category_level_kind_info_ord))+
  geom_bar(position="fill")+
  scale_fill_brewer(name="Sampling Choice Type",palette="RdYlBu")+
  xlab("Training Condition")+
  ylab("Proportion of Sampling Choices")+
  facet_wrap(~number_training_images)+
  theme_cowplot(font_size=24)+
  theme(axis.title = element_text(face="bold", size=20),
        axis.text.x  = element_text(angle=90, hjust=1,vjust=0.4))

## Sampling Choices - individual bars
sampling_data_long_structure <- expand.grid(
  participant=unique(sampling_data$participant),
  trial_counter=seq(1,6),
  sampling_choice_type = c("subordinate","basic","superordinate","outside category")
)
sampling_data_long <-  sampling_data %>%
  group_by(participant,number_training_images,trial_counter, current_category_training_level) %>%
  summarize(sampling_response = sampled_category_level_kind_info_ord)
sampling_data_long_structure <- sampling_data_long_structure %>%
  left_join(sampling_data_long) %>%
  mutate(
    sampling_choice_chosen = case_when(
      sampling_response == sampling_choice_type ~ 1,
      TRUE ~ 0
    )
  )

sampling_data_long_structure_summarized <- sampling_data_long_structure %>%
  group_by(number_training_images,current_category_training_level, sampling_choice_type) %>%
  summarize(
    N=n(),
    sampling_response_avg=mean(sampling_choice_chosen,na.rm=TRUE),
    sampling_response_total=sum(sampling_choice_chosen,na.rm=TRUE),
    sampling_response_binom_lower=binom.test(sampling_response_total,N)$conf.int[1],
    sampling_response_binom_upper=binom.test(sampling_response_total,N)$conf.int[2],
  )
sampling_data_long_structure_summarized$current_category_training_level_ord <- factor(sampling_data_long_structure_summarized$current_category_training_level,levels=c("narrow","intermediate","broad"))


ggplot(sampling_data_long_structure_summarized,aes(current_category_training_level_ord,sampling_response_avg, group=sampling_choice_type,fill=sampling_choice_type))+
  geom_errorbar(aes(ymin=sampling_response_binom_lower, ymax=sampling_response_binom_upper),width=0.3, color="black",position=position_dodge(width=0.9))+
  geom_bar(stat="identity",position=position_dodge())+
  theme_cowplot(font_size=30)+
  scale_fill_brewer(name="Sampling Choice Type",palette="RdYlBu")+
  scale_color_brewer(name="Sampling Choice Type",palette="RdYlBu")+
  xlab("Training Condition")+
  ylab("Proportion of Sampling Choices")+
  facet_wrap(~number_training_images)
```

## Test

### Plot

```{r}
## Test Plot
subj_test_prop <- test_array_options_clean %>%
  group_by(participant,number_training_images,trial_counter,current_category_training_level,current_category_label_level,current_category_kind) %>%
  summarize(
    N_subordinate = sum(test_image_type=="subordinate" & test_image_match_category==1),
    prop_subordinate = sum(test_image_type=="subordinate" & test_image_match_category==1 & is_chosen == 1)/sum(test_image_type=="subordinate" & test_image_match_category==1),
    N_basic = sum(test_image_type=="basic" & test_image_match_category==1),
    prop_basic = sum(test_image_type=="basic" & test_image_match_category==1 & is_chosen == 1)/sum(test_image_type=="basic" & test_image_match_category==1),
    N_superordinate = sum(test_image_type=="superordinate" & test_image_match_category==1),
    prop_superordinate = sum(test_image_type=="superordinate" & test_image_match_category==1 & is_chosen == 1)/sum(test_image_type=="superordinate" & test_image_match_category==1)
  )

subj_test_prop_long <- subj_test_prop %>%
  pivot_longer(N_subordinate:prop_superordinate,names_to=c(".value","choice_type"),names_sep="\\_")

overall_test_prop <- subj_test_prop %>%
  group_by(number_training_images,current_category_training_level) %>%
  summarize(
    N=n(),
    subordinate_percent = mean(prop_subordinate),
    basic_percent = mean(prop_basic),
    superordinate_percent = mean(prop_superordinate)
  )

overall_test_prop_long <- subj_test_prop_long %>%
  group_by(number_training_images,current_category_training_level,choice_type) %>%
  summarize(
    N=n(),
    avg_prop = mean(prop),
    prop_ci=qt(0.975, N-1)*sd(prop,na.rm=T)/sqrt(N),
    prop_lower_ci=avg_prop-prop_ci,
    prop_upper_ci=avg_prop+prop_ci,
  )
overall_test_prop_long$choice_type_ord <- factor(overall_test_prop_long$choice_type,levels=c("subordinate","basic","superordinate"))
overall_test_prop_long$current_category_training_level_ord <- factor(overall_test_prop_long$current_category_training_level,levels=c("narrow","intermediate","broad"))

ggplot(overall_test_prop_long,aes(choice_type_ord,avg_prop,fill=choice_type_ord))+
  geom_bar(stat="identity")+
  geom_errorbar(aes(ymin=prop_lower_ci,ymax=prop_upper_ci),width=0.1)+
  facet_wrap(~number_training_images+current_category_training_level_ord)+
  theme_cowplot(font_size=20)+
  scale_fill_manual(
    name="Test Choice Type",
    values=c("#d7191c","#fdae61","#abd9e9"))+
  xlab("Test Choice Type")+
  ylab("Average Proportion\nof Test Choices")+
  theme(axis.title = element_text(face="bold", size=24),
        axis.text.x  = element_text(angle=90, hjust=1,vjust=0.4))+
  theme(legend.position="none")
```

## Sampling by Age

### Plot

```{r fig.width=10, fig.height=4}

# pulling participant age data

participant_info <- read.csv("participant_info.csv") 
participant_ages <- participant_info %>%
  filter(pilot == "no") %>% 
  select(subject_id, age_group, age_mos, age_day_count)

# turning day counts into decimals

age_day_decimal_list <- numeric()
for (i in 1:83){
  age_day_decimal_list[[i]] <- rep(participant_ages$age_day_count[i] / 31)
}

participant_ages_decimal <- participant_ages %>% 
  mutate(age_decimal = participant_ages$age_mos+age_day_decimal_list) %>% 
  select(subject_id, age_group, age_decimal)

# combining age data with sampling data

sampling_data_ages <- sampling_data_long_structure %>% 
  mutate(age_decimal = rep(participant_ages$age_mos+age_day_decimal_list,24)) %>% 
  mutate(age_group = rep(participant_ages$age_group,24))

# summarizing

sampling_data_ages_summarized <- sampling_data_ages %>%
  group_by(age_group, 
           number_training_images,
           current_category_training_level,
           sampling_choice_type) %>% 
  summarize(
    N=n(),
    sampling_response_avg=mean(sampling_choice_chosen,na.rm=TRUE),
    sampling_response_total=sum(sampling_choice_chosen,na.rm=TRUE),
    sampling_response_binom_lower=binom.test(sampling_response_total,N)$conf.int[1],
    sampling_response_binom_upper=binom.test(sampling_response_total,N)$conf.int[2],
  ) 

sampling_data_ages_summarized$current_category_training_level <- factor(sampling_data_ages_summarized$current_category_training_level,levels=c("narrow","intermediate","broad"))

sampling_data_ages_summarized %>% filter(number_training_images == 1) %>% 
  ggplot(aes(x = age_group, 
             y = sampling_response_avg, 
             color = sampling_choice_type)) + 
  geom_point() +
  geom_line()

sampling_data_ages_summarized %>% filter(number_training_images == 3) %>% 
  ggplot(aes(x = age_group, 
             y = sampling_response_avg, 
             color = sampling_choice_type)) + 
  geom_point() +
  geom_line() + 
  facet_wrap(. ~ current_category_training_level, ncol = 3)
```