---
title: "1_pilot_exploration"
author: "Jaime Chen"
date: "2023-07-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(knitr)
knitr::opts_chunk$set(
                prompt  = FALSE,
                cache   = FALSE,
                echo = TRUE,
                warning=F,
                message=F)

library(tidyverse)
library(here)
library(janitor)
library(tidymodels)

data_path <- here("processed_data")
file_name <- "kitty-act-v1-alldata.csv"
```

# Read the data

```{r}
pilot <- read.csv(here(data_path,file_name))
```

```{r}
pilot_number_case <- pilot %>% mutate(number_object = case_when(
  number_training_image_order_vector == "[1,3]" & round == 1 ~ 1,
  number_training_image_order_vector == "[3,1]" & round == 1 ~ 3,
  number_training_image_order_vector == "[1,3]" & round == 2 ~ 3,
  number_training_image_order_vector == "[3,1]" & round == 2 ~ 1
))
```

## Looking at 3-object training data

```{r}
pilot_analysis <- pilot_number_case %>% select(
  participant,
  number_object,
  current_training_images,
  current_category_label_level,
  current_category_training_level,
  current_hypernym_category_kind,
  sampled_image,
  final_choice_array
) %>% filter(
  current_hypernym_category_kind != "" & sampled_image != "" 
  | final_choice_array != "" & sampled_image != "" ) %>% 
  group_by(
    participant,
    number_object,
    current_training_images,
    current_category_label_level,
    current_category_training_level,
    sampled_image,
    current_hypernym_category_kind,
  ) %>% 
  summarise(across(everything(), ~paste(., collapse = " "))) %>%
  ungroup(current_hypernym_category_kind) %>% 
  summarise(across(everything(), ~paste(., collapse = " ")))

pilot_analysis_samp <- pilot_analysis %>% mutate(sample_level = case_when(
  str_detect(sampled_image, "sub") == TRUE ~ "sub",
  str_detect(sampled_image, "bas") == TRUE ~ "bas",
  str_detect(sampled_image, "sup") == TRUE ~ "sup"
)) %>% mutate(confirm_choice = case_when(
  current_category_training_level == "broad" ~ "sup",
  current_category_training_level == "intermediate" ~ "bas",
  current_category_training_level == "narrow" ~ "sub"
)) %>% mutate(samp_confirm = (sample_level == confirm_choice))

# How often was a confirmatory sample choice made?
freq_confirm_num_1 <- pilot_analysis_samp %>% filter(number_object == 1) %>% pull(samp_confirm) %>% mean()*100
freq_confirm_num_3 <- pilot_analysis_samp %>% filter(number_object == 3) %>% pull(samp_confirm) %>% mean()*100
paste("When 1 training image was shown, confirmatory answers were made", round(freq_confirm_num_1, digits = 2), "% of the time. When 3 training images were shown, confirmatory answers were made", round(freq_confirm_num_3, digits = 2), "% of the time.")
```

When 1 training image was shown, confirmatory answers were made `r round(freq_confirm_num_1, digits = 2)`% of the time. When 3 training images were shown, confirmatory answers were made `r round(freq_confirm_num_3, digits = 2)`% of the time.